### ISSUE TITLE
idk if its normal but if it is i need a manual

### ISSUE THREAD

**Issue by nashoortooth** [Ero98/bitburnerHome#1]
when i execute script it get killed instant

**Comment by nashoortooth** [comment]
same for hack/hack-nodes.js i cant figure out where is the problem but it say my available money without run his while(true)

edit: i fixed it by removing ns.exit() at line 51

**Comment by Ero98** [comment]
> same for hack/hack-nodes.js i cant figure out where is the problem but it say my available money without run his while(true)
> 
> edit: i fixed it by removing ns.exit() at line 51

Sorry for the inconvenience... The Chinese output at line 50 means "The cheapest upgrade costs more than one minute to earn, the script has stopped", I've replaced it now.

**Comment by nashoortooth** [comment]
btw how master.v3 need to be used? i read every .js that you post but i dont understand why it only does autonuke

**Comment by Ero98** [comment]
> btw how master.v3 need to be used? i read every .js that you post but i dont understand why it only does autonuke

https://github.com/Ero98/bitburnerHome/blob/4ed6c5c883885a492ced72ef9884800ada2323ec/hack/bat/masterV3.js#L109-L114
The code here may take a while to run, mainly to calculate how many resources to invest into which machine.

This may cause a long pause after the script printing the line "[time] 运行开始".

You can verify if this is the case by replacing `logStr=>{}` in the code above with `log` (which is defined at the beginning of the main function), then you will see some very very verbose output (and the file `/masterV2RunInfo.txt` will gradually grow to about 80MB).

This process may take 2\~10 minutes depending on the size of all available Ram, and the CPU of your computer, mine is Intel i510400F, and had all 25 servers upgraded to maximum rams, and it took about 8\~9 minutes to process.
